show_on:
  default: discovery
  type: enum
  choices:
    - discovery
    - homepage
    - all
  description: discovery refers to topic list pages

svg_icons:
  default: 'sort-amount-up'
  type: 'list'
  list_type: 'compact'
  default: 'comments'
  type: 'list'
  list_type: 'compact'